--CRIAÇÃO DAS TABELAS CADUNI POCOBUS


CREATE TABLE felipe_abreu.usuario(
    ID INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE felipe_abreu.cartao(
    ID_CARTAO INT PRIMARY KEY IDENTITY,
    ID_PROPRIETARIO INT NOT NULL UNIQUE,
    QTDE_CREDITOS FLOAT,
    CATEGORIA VARCHAR(15) NOT NULL,
    EMISSAO DATE NOT NULL
)
GO

CREATE TABLE felipe_abreu.onibus(
    NUM_PLACA INT PRIMARY KEY IDENTITY,
    NUM_LINHA INT NOT NULL,
    MODELO_ONIBUS VARCHAR(50) NOT NULL,
    ANO_FABRICACAO DATE NOT NULL,
    ID_MOTORISTA INT NOT NULL
)
GO

CREATE TABLE felipe_abreu.motorista(
    ID_MOTORISTA INT PRIMARY KEY IDENTITY,
    NUM_CNH INT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL

)